name: invoice
build:
  docker_configs:
    - name: invoice-main
      image: australia-southeast2-docker.pkg.dev/dknathalage/invoice/invoice-main:latest
      dockerfile: Dockerfile
      context: .
      google_service_account: gha-ci-sa@dknathalage.iam.gserviceaccount.com
      google_artifact_registry: australia-southeast2-docker.pkg.dev
      google_workload_idp: projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider
