name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - uses: gwatts/go-coverage-action@v2
        id: coverage
        with:
          coverage-threshold: 80

  docker-build:
    needs:
      - test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - service1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider
          service_account: gha-ci-sa@dknathalage.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: australia-southeast2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/${{ matrix.service }}:latest
          build-args: |
            APP_NAME=${{ matrix.service }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/${{ matrix.service }}:latest
          format: "table"
          exit-code: "1"
          ignore-unfixed: false
          vuln-type: "os,library"
          severity: "LOW,MEDIUM,HIGH,CRITICAL"
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
