version: "3"

tasks:
  lint:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
      - golangci-lint run

  test:
    cmds:
      - go test -coverprofile=coverage.out -coverpkg=./pkg ./...
      - go tool cover -func=coverage.out
      # check if the coverage is less than 80%
      - go tool cover -func=coverage.out | grep total | awk '{print $3}' | awk -F. '{print $1}' | awk '{if ($1 < 80) {exit 1}}'

  sec:
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - export PATH=$PATH:$(go env GOPATH)/bin
      - $(go env GOPATH)/bin/gosec ./...

  fmt:
    cmds:
      - gofmt -s -w .

  vet:
    cmds:
      - go vet ./...

  quality:
    cmds:
      - task: go-sec
      - task: go-lint
      - task: go-test
      - task: go-vet
      - task: go-fmt

  default:
    cmds:
      - task: quality
