version: "3"

tasks:
  test.setup:
    desc: Setup
    cmds:
      - go install github.com/jstemmer/go-junit-report@latest
      - mv $(go env GOPATH)/bin/go-junit-report ~/.local/bin

  test.unit:
    desc: Run unit tests
    cmds:
      - mkdir -p reports
      - go test -v 2>&1 ./... | go-junit-report -set-exit-code > reports/junit.xml

  lint.golangci:
    desc: Run golangci-lint
    cmds:
      - $(go env GOPATH)/bin/golangci-lint run --timeout 2m
