name: Go Quality Checks 🔎
inputs:
  go-version:
    type: string
    default: "1.23"

  golint-version:
    type: string
    default: v1.61.0

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Module download
      shell: bash
      run: go mod download

    - name: Install gosec
      shell: bash
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run gosec
      shell: bash
      run: gosec ./...

    - name: Install golangci-lint
      shell: bash
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ inputs.golint-version }}

    - name: Run golangci-lint
      shell: bash
      run: golangci-lint run --timeout 2m

    - name: Run tests
      shell: bash
      run: go test -coverprofile=coverage.out -coverpkg=./pkg ./...

    - name: Coverage
      shell: bash
      run: go tool cover -func=coverage.out
