name: "Go Lint and Coverage"
description: "Runs golangci-lint and calculates coverage for Go projects"

inputs:
  go-version:
    description: "The Go version to set up."
    required: true
    default: "1.23"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
        sh -s -- -b $(go env GOPATH)/bin v1.61.0
    - shell: bash
      run: golangci-lint run
    - shell: bash
      run: go test -coverprofile=coverage.out ./...
    - shell: bash
      run: go tool cover -func=coverage.out
