name: Go Quality Checks 🔎
inputs:
  go-version:
    type: string
    default: "1.23"

  golint-version:
    type: string
    default: v1.61.0

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Module download
      shell: bash
      run: go mod download

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Run tests
      shell: bash
      run: go test -coverprofile=coverage.out -coverpkg=./pkg ./...

    - name: Coverage
      shell: bash
      run: go tool cover -func=coverage.out
