inputs:
  VULTR_API_TOKEN:
    required: true
  GCP_CTX_SERVICE_ACCOUNT:
    required: true
    default: "gha-ci-sa@dknathalage.iam.gserviceaccount.com"
  GCP_CTX_ID_PROVIDER:
    required: true
    default: "projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v1
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.GCP_CTX_ID_PROVIDER }}
        service_account: ${{ inputs.GCP_CTX_SERVICE_ACCOUNT }}
        access_token_lifetime: "300s"
    - shell: bash
      run: |
        cd ./terraform
        terraform init
    - shell: bash
      run: |
        cd ./terraform
        terraform plan -var "VULTR_API_KEY=${{ inputs.VULTR_API_TOKEN }}"
    - shell: bash
      run: |
        cd ./terraform
        terraform apply -auto-approve -var "VULTR_API_KEY=${{ inputs.VULTR_API_TOKEN }}"
