name: invoice

code:
  paths:
    - config/**/invoice**
    - .github/workflows/**
    - modules/invoice/**

images:
  - name: invoice
    dockerfile: config/docker/invoice.Dockerfile
    repo: dknathalage
    project: dknathalage
    regions:
      - australia-southeast2
    services:
      environments:
        - name: dev
        - name: np
        - name: prod
          is_public: true
