name: Build Scan Push 🚀

inputs:
  dockerfile:
    type: string
    required: true
    description: "Dockerfile path for the service"
  workload_idp:
    type: string
    required: true
    description: "Workload Identity Provider for docker login"
  service_account:
    type: string
    required: true
    description: "Service Account for docker login"
  tag:
    type: string
    required: true
    description: "Docker image tag"
  push:
    type: boolean
    default: true
    description: "Push the docker image to the registry"
  image_registry:
    type: string
    required: true
    description: "Docker image registry"
  image_name:
    type: string
    required: true
    description: "Docker image name"
  trivy_severity:
    type: string
    default: "MEDIUM,HIGH,CRITICAL"
    description: "Trivy severity levels to scan for"
  docker_context:
    type: string
    default: "."
    description: "Docker build context"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.workload_idp }}
        service_account: ${{ inputs.service_account }}
        access_token_lifetime: "300s"

    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.image_registry }}
        username: "oauth2accesstoken"
        password: ${{ steps.auth.outputs.access_token }}

    - id: check-image
      name: Check if image exists and save to GITHUB_OUTPUT
      run: |
        if docker manifest inspect ${{ inputs.image_name }}:${{ inputs.tag }}
        then
          echo "exists=true">> $GITHUB_OUTPUT
        else
          echo "exists=false">> $GITHUB_OUTPUT
        fi
      shell: bash

    - if: ${{ steps.check-image.outputs.exists == 'false' }}
      run: |
        docker build \
          -t ${{ inputs.image_name }}:${{ inputs.tag }} \
          -f ${{ inputs.dockerfile }} \
          --cache-from ${{ inputs.image_name }}:build-cache \
          --cache-to ${{ inputs.image_name }}:build-cache,mode=max \
          ${{ inputs.docker_context }}

    - env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
      id: trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        exit-code: "1"
        format: table
        ignore-unfixed: false
        image-ref: ${{ inputs.image_name }}:${{ inputs.tag }}
        severity: ${{ inputs.trivy_severity }}
        vuln-type: os,library

    - if: ${{ inputs.push == true }}
      run: |
        docker push ${{ inputs.image_name }}:${{ inputs.tag }}
