apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-cloud-run
  labels:
    cloud.googleapis.com/location: australia-southeast2
spec:
  template:
    spec:
      containers:
        - image: "gcr.io/cloudrun/hello"
  traffic:
    - latestRevision: false
      percent: 0
