on:
  workflow_call:

env:
  GCP_CTX_SERVICE_ACCOUNT: gha-ci-sa@dknathalage.iam.gserviceaccount.com
  GCP_CTX_ID_PROVIDER: projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v1

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.GCP_CTX_ID_PROVIDER }}
          service_account: ${{ env.GCP_CTX_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - run: terraform init

      - run: terraform plan -var "VULTR_API_KEY=${{ secrets.VULTR_API_TOKEN }}"

      - run: terraform apply -auto-approve -var "VULTR_API_KEY=${{ secrets.VULTR_API_TOKEN }}"
