on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
      server_ip:
        type: string
        required: true
    secrets:
      VULTR_SSH_KEY:
        required: true

env:
  GCP_CTX_SERVICE_ACCOUNT: gha-ci-sa@dknathalage.iam.gserviceaccount.com
  GCP_CTX_ID_PROVIDER: projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider
  GCP_CTX_GAR_REGISTRY: australia-southeast2-docker.pkg.dev
  GCP_CTX_GAR_REPOSITORY: dknathalage/dknathalage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.GCP_CTX_ID_PROVIDER }}
          service_account: ${{ env.GCP_CTX_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - id: image_base
        run: echo IMAGE_BASE=${{ env.GCP_CTX_GAR_REGISTRY }}/${{ env.GCP_CTX_GAR_REPOSITORY }}/${{ inputs.service }} >> $GITHUB_ENV

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.server_ip }}
          username: root
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin ${{ env.GCP_CTX_GAR_REGISTRY }}
            docker pull ${{ steps.image_base.outputs.IMAGE_BASE }}:latest
