name: CI/CD Pipeline
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  id-token: write

concurrency:
  group: ci-services
  cancel-in-progress: true

jobs:
  docker-build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'build')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: "invoice"
            dockerfile: "./cmd/invoice/Dockerfile"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider"
          service_account: "gha-ci-sa@dknathalage.iam.gserviceaccount.com"
          access_token_lifetime: "300s"

      - uses: docker/login-action@v2
        with:
          registry: "australia-southeast2-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:latest
            ${{ env.IMAGE_BASE }}:${{ github.sha }}
          file: ${{ matrix.service.dockerfile }}
          context: .
          cache-from: type=registry,ref=${{ env.IMAGE_BASE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_BASE }}:buildcache,mode=max
        env:
          IMAGE_BASE: "australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/${{ matrix.service.name }}"

  cloudrun-deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy')
    needs: docker-build
    strategy:
      matrix:
        service:
          - name: "invoice"
            allow_unauthenticated: true
            concurrency: 80
            max_instances: 1
            cpu: 1
            memory: 1Gi

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider"
          service_account: "gha-ci-sa@dknathalage.iam.gserviceaccount.com"
          access_token_lifetime: "300s"

      - uses: "google-github-actions/setup-gcloud@v2"

      - run: |
          gcloud run deploy ${{ matrix.service.name }} \
          --image ${{ env.IMAGE_BASE }}:${{ github.sha }} \
          --platform managed \
          --region australia-southeast2 \
          --allow-unauthenticated \
          --concurrency ${{ matrix.service.concurrency }} \
          --port 80 \
          --cpu ${{ matrix.service.cpu }} \
          --memory ${{ matrix.service.memory }} \
          --max-instances ${{ matrix.service.max_instances }}
        env:
          IMAGE_BASE: "australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/${{ matrix.service.name }}"
