name: CI/CD Pipeline
on:
  push:
    branches:
      - main
    paths:
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/ci-services.yaml"

  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: ci-services
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      - run: task setup.lint
      - run: task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      - run: task setup.test
      - run: task test

  sec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      - run: task setup.sec
      - run: task sec

  docker-build:
    needs:
      - lint
      - test
      - sec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SERVICE_NAME:
          - "invoice"
        DOCKERFILE:
          - "./cmd/invoice/Dockerfile"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider"
          service_account: "gha-ci-sa@dknathalage.iam.gserviceaccount.com"
          access_token_lifetime: "300s"
      - uses: docker/login-action@v2
        with:
          registry: "australia-southeast2-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: ${{ steps.auth.outputs.access_token }}
      - id: image_base
        shell: bash
        run: echo IMAGE_BASE="australia-southeast2-docker.pkg.dev"/"dknathalage/dknathalage"/${{ matrix.SERVICE_NAME }} >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.image_base.outputs.IMAGE_BASE }}:latest
            ${{ steps.image_base.outputs.IMAGE_BASE }}:${{ github.sha }}
          file: ${{ matrix.DOCKERFILE }}
          context: .
          cache-from: type=registry,ref=${{ steps.image_base.outputs.IMAGE_BASE }}:buildcache
          cache-to: type=registry,ref=${{ steps.image_base.outputs.IMAGE_BASE }}:buildcache,mode=max

  cloudrun-deploy:
    needs:
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider"
          service_account: "gha-ci-sa@dknathalage.iam.gserviceaccount.com"
          access_token_lifetime: "300s"
      - uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "hello-cloud-run"
          image: "gcr.io/cloudrun/hello"
          project_id: "dknathalage"
