on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  quality-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1
      - run: task go-lint

  quality-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - shell: bash
        run: go test -coverprofile=coverage.out ./...
      - shell: bash
        run: go tool cover -func=coverage.out

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tf-deploy
        with:
          VULTR_API_TOKEN: ${{ secrets.VULTR_API_TOKEN }}

  docker-build:
    needs:
      - quality-lint
      - quality-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          SERVICE_NAME: test
          DOCKERFILE: ./cmd/data/Dockerfile

  vultr-services:
    needs: [terraform, docker-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/vultr-deploy
        with:
          SERVICE: test
          SERVER_IP: 67.219.103.200
          VULTR_SSH_KEY: ${{ secrets.VULTR_SSH_KEY }}
