on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/go-quality

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tf-deploy
        with:
          VULTR_API_TOKEN: ${{ secrets.VULTR_API_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          service: test
          dockerfile: ./cmd/test/Dockerfile

  vultr-services:
    needs: [terraform, docker-build]
    uses: dknathalage/dknathalage/.github/workflows/cd-vultr.yaml@main
    with:
      service: test
      server_ip: 67.219.103.200
    secrets:
      VULTR_SSH_KEY: ${{ secrets.VULTR_SSH_KEY }}
