name: CI Workflow 🛠️

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

  release:

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

env:
  WORKLOAD_IDP: "projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider"
  SERVICE_ACCOUNT: "gha-ci-sa@dknathalage.iam.gserviceaccount.com"
  REGISTRY_URL: "australia-southeast2-docker.pkg.dev"
  IMAGE_PREFIX: "australia-southeast2-docker.pkg.dev/dknathalage/dknathalage"

jobs:
  quality:
    if: ${{ !contains(github.event.pull_request.labels.*.name , 'skip-ci')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/go-quality

  build:
    if: ${{ !contains(github.event.pull_request.labels.*.name , 'skip-ci')}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: invoice
            dockerfile: ./cmd/invoice/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-scan-push
        with:
          dockerfile: ${{ matrix.service.dockerfile }}
          workload_idp: ${{ env.WORKLOAD_IDP }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          image_registry: ${{ env.REGISTRY_URL }}
          image_name: ${{ env.IMAGE_PREFIX }}/${{ matrix.service.name}}
          tag: ${{ github.sha }}
          push: ${{ contains(github.event.pull_request.labels.*.name , 'deploy') || github.event_name == 'release' }}

  deploy:
    if: ${{ !contains(github.event.pull_request.labels.*.name , 'skip-ci') && (contains(github.event.pull_request.labels.*.name , 'deploy') || github.event_name == 'release') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: invoice
            region: australia-southeast2

    needs: build
    steps:
      - uses: actions/checkout@v4

      - run: |
          if ${{ github.event_name == 'release' }}; then
            TAG=tag_${{ github.event.release.tag_name }}
          else
            TAG=pr_${{ github.event.pull_request.number }}
          fi
          echo TAG=$TAG >> $GITHUB_OUTPUT
          echo IMAGE_WITH_SHA=${{ env.IMAGE_PREFIX }}/${{ matrix.service.name }}:${{ github.sha }} >> $GITHUB_OUTPUT
          echo IMAGE_WITH_TAG=${{ env.IMAGE_PREFIX }}/${{ matrix.service.name }}:$TAG >> $GITHUB_OUTPUT
        id: inputs

      - uses: ./.github/actions/deploy-cloudrun
        with:
          workload_idp: ${{ env.WORKLOAD_IDP }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          service_name: ${{ matrix.service.name }}
          region: ${{ matrix.service.region }}
          image: ${{ steps.inputs.outputs.IMAGE_WITH_SHA }}

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.WORKLOAD_IDP }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: "300s"

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: "oauth2accesstoken"
          password: ${{ steps.auth.outputs.access_token }}

      - run: |
          gcloud run services update ${{ matrix.service.name }} --platform=managed --region=australia-southeast2 --tag=${{ steps.inputs.outputs.TAG }} --no-traffic

      - run: |
          docker pull ${{ steps.inputs.outputs.IMAGE_WITH_SHA }}
          docker tag ${{ steps.inputs.outputs.IMAGE_WITH_SHA }} ${{ steps.inputs.outputs.IMAGE_WITH_TAG }}
          docker push ${{ steps.inputs.outputs.IMAGE_WITH_TAG }}
