name: CI/CD Pipeline

on:
  push:
    paths:
      - .github/workflows/cicd.yaml
      - modules/**
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit-test:
    uses: ./.github/workflows/go-quality.yaml

  invs-build:
    uses: ./.github/workflows/reuse-docker-build-push.yaml
    with:
      dockerfile: ./modules/invoissential-web/Dockerfile
      idp: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
      sa: gha-ci-sa@dknathalage.iam.gserviceaccount.com
      region: australia-southeast1
      image_name: australia-southeast1-docker.pkg.dev/dknathalage/dknathalage/invoissential/web:${{ github.sha }}
      docker_context: ./modules/invoissential-web
