name: CI/CD Pipeline

on:
  push:
    paths:
      - .github/workflows/cicd.yaml
      - .github/workflows/reuse-docker-build-push.yaml
      - .github/workflows/reuse-terraform-plan-apply.yaml
      - modules/**
      - infra/**
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docker-builds:
    uses: ./.github/workflows/reuse-docker-build-push.yaml
    strategy:
      matrix:
        images:
          - name: invoissential/web
            context: ./modules/invoissential-web
            dockerfile: ./modules/invoissential-web/Dockerfile
    with:
      idp: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
      sa: gha-ci-sa@dknathalage.iam.gserviceaccount.com
      region: australia-southeast1
      dockerfile: ${{ matrix.images.dockerfile }}
      image_name: australia-southeast1-docker.pkg.dev/dknathalage/dknathalage/${{ matrix.images.name }}:${{ github.sha }}
      docker_context: ${{ matrix.images.context }}

  dev-tf:
    needs: docker-builds
    uses: ./.github/workflows/reuse-terraform-plan-apply.yaml
    with:
      workload_idp: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
      ci_sa: gha-ci-sa@dknathalage.iam.gserviceaccount.com
      tfvars: dev.tfvars
      environment: dev
      folder: infra

  np-tf:
    needs: dev-tf
    uses: ./.github/workflows/reuse-terraform-plan-apply.yaml
    with:
      workload_idp: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
      ci_sa: gha-ci-sa@dknathalage.iam.gserviceaccount.com
      tfvars: np.tfvars
      environment: np
      folder: infra

  prod-tf:
    needs: np-tf
    uses: ./.github/workflows/reuse-terraform-plan-apply.yaml
    with:
      workload_idp: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
      ci_sa: gha-ci-sa@dknathalage.iam.gserviceaccount.com
      tfvars: prod.tfvars
      environment: prod
      folder: infra
