name: CI/CD Pipeline

on:
  push:
    paths:
      - modules/**
      - .github/workflows/cicd.yaml

permissions:
  contents: read
  actions: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  WORKLOAD_IDP: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
  CI_SA: gha-ci-sa@dknathalage.iam.gserviceaccount.com
  GAR_REGISTRY: australia-southeast2-docker.pkg.dev
  IMAGE_PREFIX: australia-southeast2-docker.pkg.dev/dknathalage/dknathalage
  REGION: australia-southeast2
  CLOUDRUN_FLAGS: ""

jobs:
  unit-test:
    name: Unit Test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Go 🐹
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Task 📦
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Run Unit Tests 🧪
        run: task test.setup test.unit

      - name: Unit Test Report 📊
        run: |
          cat ./reports/test_report.md >> $GITHUB_STEP_SUMMARY

      - name: GolangCI-Lint 📦
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  build-deploy:
    name: Build Deploy 🚀
    strategy:
      fail-fast: false
      matrix:
        service:
          - invoice
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🏗️
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry 🛅
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDP }}
          service_account: ${{ env.CI_SA }}
          access_token_lifetime: 300s

      - name: Login to Docker 🐳
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Variables 🧮
        id: vars
        run: |
          echo IMAGE=${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }} >> $GITHUB_OUTPUT
          echo TAG=$(echo ${{github.ref}} | sed 's/\//-/g') >> $GITHUB_OUTPUT
          echo "IMAGE_EXISTS=$(docker manifest inspect ${IMAGE_PREFIX}/${MATRIX_SERVICE}:${GITHUB_SHA} > /dev/null 2>&1 && echo 0 || echo 1)" >> $GITHUB_OUTPUT
      - name: Build Docker Image 🐳
        if: steps.vars.outputs.IMAGE_EXISTS == 0
        shell: bash
        run: |
          docker build \
            -t ${{ steps.vars.outputs.IMAGE }} \
            -f ./config/docker/${{ matrix.service }}.Dockerfile .

      - name: Pull Docker Image 📥
        if: steps.vars.outputs.IMAGE_EXISTS == 1
        run: |
          docker pull ${{ steps.vars.outputs.IMAGE }}

      - name: Push Docker Image 🚀
        run: |
          docker push ${{ steps.vars.outputs.IMAGE }}
          rm -rf ./reports && mkdir -p ./reports

      - name: Scan Docker Image 🕵
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
        id: trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          exit-code: 1
          format: table
          ignore-unfixed: true
          image-ref: ${{ steps.vars.outputs.IMAGE }}
          severity: HIGH,CRITICAL
          vuln-type: os,library
          output: ./reports/trivy-report.txt

      - name: Output step summary
        run: |
          echo "**Trivy Config Scan Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat ./reports/trivy-report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Deploy to CloudRun 🚀
        run: |
          gcloud run deploy ${{ matrix.service }} \ 
            --image ${{ steps.vars.outputs.IMAGE }} \
            --region ${{ env.REGION }} \ 
            ${{ env.CLOUDRUN_FLAGS }} \
            --tag ${{ steps.vars.outputs.TAG }}

      - name: Update Traffic 🚦
        run: gcloud run services update-traffic ${{ matrix.service }} --platform managed --region australia-southeast2 --tag ${{ steps.vars.outputs.TAG }}

      - name: Pull Tag Push 🚀
        run: |
          docker pull ${{ env.IMAGE_PREFIX }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}:${{ github.sha }} ${{ env.IMAGE_PREFIX }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ env.IMAGE_PREFIX }}:${{ steps.vars.outputs.TAG }}
