on:
  workflow_call:
    inputs:
      registry:
        description: Google Artifact Registry
        default: australia-southeast2-docker.pkg.dev
        type: string
      workload_identity_provider:
        description: Workload Identity Pool Provider for Google Artifact Registry
        default: projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider
        type: string
      service_account:
        description: Service Account for Google Artifact Registry
        default: gha-ci-sa@dknathalage.iam.gserviceaccount.com
        type: string
      project:
        description: Google Cloud Project
        default: dknathalage
        type: string
      registry_name:
        description: Google Artifact Registry Name
        default: dknathalage
        type: string
      service:
        description: Service Name
        required: true
        type: string
      dockerfile:
        description: Path to the Dockerfile
        required: true
        type: string

env:
  IMAGE_REGISTRY: ${{ inputs.registry }}/${{ inputs.project }}/${{ inputs.registry_name }}
  IMAGE_PREFIX: ${{ inputs.registry }}/${{ inputs.project }}/${{ inputs.registry_name }}/${{ inputs.service }}

jobs:
  build:
    name: Docker Build Push 🐳
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🏗️
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry 🛅
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: 300s

      - name: Login to Docker 🐳
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Check If Image Exists 🖼️
        id: check
        run: |
          echo image_exists=$(docker manifest inspect ${{ env.IMAGE_PREFIX }}:${{ github.sha }} > /dev/null 2>&1; echo $?) >> $GITHUB_OUTPUT

      - name: Build Docker Image 🐳
        if: steps.check.outputs.image_exists == 1
        shell: bash
        run: |
          docker build \
            -t ${{ env.IMAGE_PREFIX }}:${{ github.sha }} \
            -f ${{ inputs.dockerfile }} \

      - name: Pull Docker Image 📥
        if: steps.check.outputs.image_exists == 0
        run: |
          docker pull ${{ env.IMAGE_PREFIX }}:${{ github.sha }}

      - name: Push Docker Image 🚀
        run: |
          docker push ${{ env.IMAGE_PREFIX }}:${{ github.sha }}
          rm -rf ./reports && mkdir -p ./reports

      - name: Scan Docker Image 🕵
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
        id: trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          exit-code: 1
          format: table
          ignore-unfixed: true
          image-ref: ${{ env.IMAGE_PREFIX }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          vuln-type: os,library
          output: ./reports/trivy-report.txt

      - name: Output step summary
        run: |
          echo "**Trivy Config Scan Summary**" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat ./reports/trivy-report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  deploy:
    name: Deploy to CloudRun 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Login to Google Cloud 🌐
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: 300s

      - name: Setup Google Cloud SDK 🛠️
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to CloudRun 🚀
        run: gcloud run deploy ${{ inputs.service }} --image ${{ env.IMAGE_PREFIX }}:${{ github.sha }} --region australia-southeast2

  tag_versioning:
    name: Tagging 🏷️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🏗️
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry 🛅
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          access_token_lifetime: 300s

      - name: Login to Docker 🐳
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: version
        run: echo TAG=$(echo ${{github.ref}} | sed 's/\//-/g') >> $GITHUB_OUTPUT

      - name: Pull Tag Push 🚀
        run: |
          docker pull ${{ env.IMAGE_PREFIX }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}:${{ github.sha }} ${{ env.IMAGE_PREFIX }}:${{ steps.version.outputs.TAG }}
          docker push ${{ env.IMAGE_PREFIX }}:${{ steps.version.outputs.TAG }}
