name: Go Quality Workflow 🧪

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"

jobs:
  unit-test:
    name: Unit Test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Go 🐹
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install Task 📦
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Run Unit Tests 🧪
        run: task test.unit

  lint:
    name: Lint 🧹
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Go 🐹
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install GolangCI-Lint 📦
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
