name: Go Quality Workflow 🧪

on:
  workflow_call:
    inputs:
      release_version:
        description: "Release version"
        type: string
      go_version:
        description: "Go version"
        default: "1.23"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  artifacts:
    name: Artifacts 🎨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Setup
        shell: bash
        run: |
          echo ${{ github.event_name }}

  unit-test:
    name: Unit Test 🧪
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Go 🐹
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go_version }}

      - name: Install Task 📦
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Run Unit Tests 🧪
        run: task test.setup test.unit

      - uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: junit.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: JEST Tests
          path: junit.xml
          reporter: java-junit

  lint:
    name: Lint 🧹
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Go 🐹
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go_version }}

      - name: Install GolangCI-Lint 📦
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
