jobs:
  docker-build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          access_token_lifetime: 300s
          service_account: gha-ci-sa@dknathalage.iam.gserviceaccount.com
          token_format: access_token
          workload_identity_provider: projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider
      - uses: docker/login-action@v1
        with:
          password: ${{ steps.auth.outputs.access_token }}
          registry: australia-southeast2-docker.pkg.dev
          username: oauth2accesstoken
      - uses: docker/build-push-action@v2
        with:
          build-args: APP_NAME=${{ matrix.service }}
          push: true
          tags: australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/${{matrix.service}}:latest
      - env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
        uses: aquasecurity/trivy-action@0.20.0
        with:
          exit-code: "1"
          format: table
          ignore-unfixed: false
          image-ref: australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/${{matrix.service}}:latest
          severity: LOW,MEDIUM,HIGH,CRITICAL
          vuln-type: os,library
    strategy:
      matrix:
        service:
          - service
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: "1.23"
      - run: go mod download
      - run: go test ./...
      - uses: gwatts/go-coverage-action@v2
        with:
          coverage-threshold: 80
"on":
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
