on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/719430876063/locations/global/workloadIdentityPools/dknathalage-identity-pool/providers/dknathalage-id-provider
          service_account: gha-ci-sa@dknathalage.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: australia-southeast2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/test:${{ github.sha }}
            australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/test:latest
          file: ./cmd/data/Dockerfile
          context: .

      - name: SSH to Vultr and deploy docker container
        uses: appleboy/ssh-action@master
        with:
          host: 67.219.109.47
          username: root
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin australia-southeast2-docker.pkg.dev
            docker pull australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/test:latest
            docker stop $(docker ps -q)
            docker run -d -p 80:80 australia-southeast2-docker.pkg.dev/dknathalage/dknathalage/test:latest
