on:
  push:
    branches:
      - main

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://sjc.vultrcr.com/dknathalageregistry
          username: 0004d5b6-241c-4a83-b639-d5e45949bb2d
          password: ${{ secrets.VULTR_REGISTRY_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            sjc.vultrcr.com/dknathalageregistry/test:latest
            sjc.vultrcr.com/dknathalageregistry/test:${{ github.sha }}
          file: ./cmd/data/Dockerfile
          context: .

      - name: SSH to Vultr and deploy docker container
        uses: appleboy/ssh-action@master
        with:
          host: 67.219.109.47
          username: root
          key: ${{ secrets.VULTR_SSH_KEY }}
          script: |
            cat ${{ secrets.VULTR_REGISTRY_PASS }} | docker login -u 0004d5b6-241c-4a83-b639-d5e45949bb2d --password-stdin sjc.vultrcr.com
            docker pull sjc.vultrcr.com/dknathalageregistry/test:latest
            docker stop $(docker ps -q)
            docker run -d -p 80:80 sjc.vultrcr.com/dknathalageregistry/test:latest
