name: Assign PR Labels

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  asign-pr-labels:
    runs-on: ubuntu-latest
    steps:
      - id: action-assign-labels
        uses: mauroalderete/action-assign-labels@v1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'go changes'
                nouns: ['go', 'GO', 'Golang']
                labels: ['go', 'build', 'deploy']
              - type: 'image changes'
                nouns: ['image', 'images', 'img', 'imgs']
                labels: ['image', 'deploy']
          maintain-labels-not-matched: false
          apply-changes: true
