on:
  workflow_call:

jobs:
  unit-test:
    name: Unit Test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v4

      - name: Set up Go 🐹
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Task 📦
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Run Unit Tests 🧪
        run: task test.setup test.unit

      - name: Unit Test Report 📊
        run: |
          cat ./reports/test_report.md >> $GITHUB_STEP_SUMMARY

      - name: GolangCI-Lint 📦
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
