name: Tagging 🏷️

# Trigger the workflow on push to main or manually via workflow_dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define permissions
permissions:
  contents: write
  pull-requests: write

# Set environment variables
env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  prerelease:
    # Run this job only on push events
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Current Version
        id: get_current_version
        run: echo "CURRENT_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - id: is_tag_has_rc
        run: |
          if [[ ${{ steps.get_current_version.outputs.CURRENT_VERSION }} == *"rc"* ]]; then
            echo "Tag has rc"
            echo "IS_RC=true" >> $GITHUB_OUTPUT
          else
            echo "Tag does not have rc"
            echo "IS_RC=false" >> $GITHUB_OUTPUT
          fi

      - name: Bump Version for Pre-release
        id: bump_version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ steps.get_current_version.outputs.CURRENT_VERSION }}
          increment-version-fragment: ${{ steps.is_tag_has_rc.outputs.IS_RC == 'true' && 'NONE' || 'MINOR' }}
          prerelease-fragment: "RC"

      - name: Create Pre-release Tag
        run: |
          git tag -a -m "Release ${{ steps.bump_version.outputs.updated-version }}" ${{ steps.bump_version.outputs.updated-version }}
          git push origin ${{ steps.bump_version.outputs.updated-version }}

      - name: Create Release
        run: |
          gh release create ${{ steps.bump_version.outputs.updated-version }} --title "Release ${{ steps.bump_version.outputs.updated-version }}" --notes "Release ${{ steps.bump_version.outputs.updated-version }}" --prerelease

      - name: Delete existing Pre-release
        if: ${{ steps.is_tag_has_rc.outputs.IS_RC == 'true' }}
        run: |
          gh release delete ${{ steps.get_current_version.outputs.CURRENT_VERSION }}

  release:
    # Run this job only when manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Current Version
        id: get_current_version
        run: echo "CURRENT_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Bump Version for Release
        id: bump_version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: ${{ steps.get_current_version.outputs.CURRENT_VERSION }}
          increment-version-fragment: "NONE"
          prerelease-fragment: "REMOVE"

      - name: Create Release Tag
        run: |
          new_tag="v${{ steps.bump_version.outputs.updated-version }}"
          git tag -a -m "Release $new_tag" $new_tag
          git push origin $new_tag

      - name: Create Release
        run: |
          gh release create ${{ steps.bump_version.outputs.updated-version }} --title "Release ${{ steps.bump_version.outputs.updated-version }}" --notes "Release ${{ steps.bump_version.outputs.updated-version }}"
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}

      - id: is_tag_has_rc
        run: |
          if [[ ${{ steps.get_current_version.outputs.CURRENT_VERSION }} == *"rc"* ]]; then
            echo "Tag has rc"
            echo "IS_RC=true" >> $GITHUB_OUTPUT
          else
            echo "Tag does not have rc"
            echo "IS_RC=false" >> $GITHUB_OUTPUT
          fi

      - name: Delete existing Pre-release
        if: ${{ steps.is_tag_has_rc.outputs.IS_RC == 'true' }}
        run: |
          gh release delete ${{ steps.get_current_version.outputs.CURRENT_VERSION }}
