name: Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: tag-create
        run: |
          git tag ${{ steps.semver.outputs.next }}

      - name: tag-push
        run: |
          git push origin ${{ steps.semver.outputs.next }}
