on:
  push:
    branches:
      - minor-fix

  workflow_dispatch:

jobs:
  prerelease-bumps:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/minor-fix' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Repo SemVer
        uses: lhstrh/action-repo-semver@v1.1.2
        id: repo-semver
        with:
          bump: minor

  release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Repo SemVer
        uses: lhstrh/action-repo-semver@v1.1.2
        id: repo-semver
        with:
          bump: release
