name: Terraform 🏗

on:
  push:
    paths:
      - infra/**
      - .github/workflows/terraform.yaml

env:
  WORKLOAD_IDP: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
  CI_SA: gha-ci-sa@dknathalage.iam.gserviceaccount.com

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  tf-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v1
      - uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDP }}
          service_account: ${{ env.CI_SA }}
          access_token_lifetime: 300s
      - run: terraform -chdir=./infra/shared init
      - run: terraform -chdir=./infra/shared plan
      - run: terraform -chdir=./infra/shared apply --auto-approve
