on:
  workflow_call:
    inputs:
      workload_idp:
        description: "Workload Identity Pool ID"
        required: true
        type: string
      ci_sa:
        description: "Service Account for CI"
        required: true
        type: string
      folder:
        description: "Folder containing Terraform configuration"
        default: ""
        type: string
      tfvars:
        description: "Terraform variables file"
        required: true
        type: string
      environment:
        description: "Environment"
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false
      - uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_idp }}
          service_account: ${{ inputs.ci_sa }}
          access_token_lifetime: 600s
      - run: |
          rm -rf .terraform
          terraform init -upgrade
          terraform plan -var-file=./tfvars/${{ inputs.tfvars }} \
                         -var-file=./tfvars/common.tfvars \
                         -out=tfplan.plan
          terraform show -no-color -json tfplan.plan > tfplan.json
        working-directory: ${{ inputs.folder }}
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}-tfplan
          path: ${{ inputs.folder }}/tfplan.plan
          retention-days: 1
      - uses: liatrio/terraform-change-pr-commenter@v1.7.0
        with:
          json-file: ${{ inputs.folder }}/tfplan.json
          include-plan-job-summary: true
          include-workflow-link: true

  apply:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_idp }}
          service_account: ${{ inputs.ci_sa }}
          access_token_lifetime: 600s
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.environment }}-tfplan
      - run: |
          rm -rf .terraform
          terraform init -upgrade
          terraform apply -auto-approve tfplan.plan
