name: Terraform 🏗

on:
  push:
    paths:
      - infra/**
      - .github/workflows/terraform.yaml
  release:
    types:
      - published

env:
  WORKLOAD_IDP: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
  CI_SA: gha-ci-sa@dknathalage.iam.gserviceaccount.com

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  plan:
    strategy:
      fail-fast: false
      matrix:
        module:
          - folder: shared
            tfvars: shared.tfvars
          - folder: environment
            tfvars: dev.tfvars
          - folder: environment
            tfvars: np.tfvars
          - folder: environment
            tfvars: prod.tfvars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v1
      - uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDP }}
          service_account: ${{ env.CI_SA }}
          access_token_lifetime: 300s
      - run: terraform init -reconfigure
        working-directory: ./infra/${{ matrix.module.folder }}
      - run: terraform plan -var-file=./tfvars/${{ matrix.module.tfvars }} -var-file=./tfvars/common.tfvars -lock=false -out=plan.out
        working-directory: ./infra/${{ matrix.module.folder }}
      - run: terraform show -json plan.out > plan.json
        working-directory: ./infra/${{ matrix.module.folder }}
      - uses: liatrio/terraform-change-pr-commenter@v1.4.0
        with:
          json-file: plan.json
          expand-comment: "true"
          include-plan-job-summary: "true"
