name: Terraform 🏗

on:
  push:
    paths:
      - infra/**
      - .github/workflows/terraform.yaml
      - .github/workflows/terraform-plan-apply.yaml
  release:
    types:
      - published

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  plan-apply:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        module:
          - tfvars: dev.tfvars
          - tfvars: np.tfvars
          - tfvars: prod.tfvars
    uses: dknathalage/dknathalage/.github/workflows/terraform-plan-apply.yaml@main
    with:
      workload_idp: projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions
      ci_sa: gha-ci-sa@dknathalage.iam.gserviceaccount.com
      tfvars: ${{ matrix.module.tfvars }}
