"env":
  "CI_SA": "gha-ci-sa@dknathalage.iam.gserviceaccount.com"
  "WORKLOAD_IDP": "projects/719430876063/locations/global/workloadIdentityPools/id-pool/providers/github-actions"
"jobs":
  "build":
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "Checkout \U0001F4E5"
      "uses": "actions/checkout@v4"
    - "name": "Set up Docker Buildx \U0001F3D7️"
      "uses": "docker/setup-buildx-action@v3"
    - "id": "auth"
      "name": "Login to Google Cloud \U0001F310"
      "uses": "google-github-actions/auth@v2"
      "with":
        "access_token_lifetime": "300s"
        "project_id": "dknathalage"
        "service_account": "$env.CI_SA"
        "token_format": "access_token"
        "workload_identity_provider": "$env.WORKLOAD_IDP"
    - "name": "Login to Docker \U0001F433"
      "uses": "docker/login-action@v3"
      "with":
        "password": "$steps.auth.outputs.access_token"
        "registry": "australia-southeast1-docker.pkg.dev"
        "username": "oauth2accesstoken"
    - "name": "Build Docker Image \U0001F3D7️"
      "run": "docker build -t australia-southeast1-docker.pkg.dev/invoice:$github.sha
        -f config/docker/invoice.Dockerfile ."
    - "name": "Push Docker Image \U0001F4E4"
      "run": "docker push australia-southeast1-docker.pkg.dev/invoice:$github.sha"
"name": "TF Gen invoice Build \U0001F3D7️"
"on":
  "push":
    "paths":
    - "config/**/invoice**"
    - ".github/workflows/**"
    - "modules/invoice/**"
  "workflow_dispatch": {}
"permissions":
  "actions": "read"
  "contents": "read"
  "id-token": "write"
