name: go-scans

inputs:
  go-version:
    description: "The Go version to use"
    default: "1.23"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - uses: golangci/golangci-lint-action@v6

    - run: go mod download
    - run: go test -v ./...
    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        coverage-threshold: 80

    - uses: securego/gosec@master
      with:
        args: "-no-fail -fmt sarif -out results.sarif ./..."

    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
        category: gosec
